INSERT INTO `Address` (`id`, `city`, `details`) VALUES (1, 'София', 'бул. Витоша 12');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (2, 'София', 'ж.к. Овча Купел 1, бл. 411, вх. А, ап. 11');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (3, 'София', 'ж.к. Надежда, бл. 11, вх. 3');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (4, 'Пловдив', 'ул. Ген. Гурко 23');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (5, 'Пловдив', 'ул. Май 11');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (6, 'Плевен', 'ул. Св. Кирил и Методий 23');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (7, 'Плевен', 'ул. Цар Симеон 11');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (8, 'Варна', 'ул. Македония 3');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (9, 'Велико Търново', 'ул. Хан Аспарух 11');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (10, 'Бургас', 'ул. Сердика 13');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (11, 'Стара Загора', 'ул. Цар Калоян 12');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (12, 'София', 'зала Универсиада');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (13, 'София', 'НС "Васил Левски"');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (14, 'София', 'стадион "Георги Аспарухов"');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (15, 'София', 'стадион "Академик"');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (16, 'Пловдив', 'стадион "Ботев"');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (17, 'Варна', 'стадион "Тича"');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (18, 'Велико Търново', 'стадион "Ивайло"');
INSERT INTO `Address` (`id`, `city`, `details`) VALUES (19, 'Варна', 'Дворец на културата и спорта');
